services:
  - type: web
    name: doodledash-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/drawings
    envVars:
      - key: APP_CORS_ALLOWED_ORIGIN
        value: https://doodledash-frontend.onrender.com

  - type: web
    name: doodledash-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://doodledash-backend.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://doodledash-backend.onrender.com/ws
